### ISSUE TITLE
Numpy put method being correctly used?

### ISSUE THREAD

**Issue by Draichi** [notadamking/Stock-Trading-Visualization#1]
Nice project mate,

After making some tests i'm having a problem, I think you are updating only the first and the 3th values on line https://github.com/notadamking/Stock-Trading-Visualization/blob/39ed1d4dc4ce734853f76a3256ed6de5ee963192/env/StockTradingEnv.py#L58 
Is that right?
here is the documentation
https://docs.scipy.org/doc/numpy/reference/generated/numpy.put.html

I'm trying to understand what's happening here, i'm looking forward for you answer, thanks

**Comment by notadamking** [comment]
Ah, looks like you are correct. It should instead be `np.put(frame, [0,1,2,3,4], [...`.

**Comment by notadamking** [comment]
I have updated the repo, thanks for the catch!
